#!/usr/bin/env bash
set -e
pushd ~/nixos/
alejandra . &>/dev/null
echo "NixOS Rebuilding..."
git add .
sudo nixos-rebuild switch --flake . &>nixos-switch.log || (
 cat nixos-switch.log | grep --color error && false)
gen=$(nixos-rebuild list-generations | grep current)
git commit -am "$gen"
popd